package entity;
// Generated May 8, 2017 8:56:39 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Clinic generated by hbm2java
 */
public class Clinic implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7025283168242715919L;
	private int idClinic;
	private String address;
	private String nameClinic;
	private Set<Doctor> doctors = new HashSet<>(0);

	public Clinic() {
	}

	public Clinic(int idClinic) {
		this.idClinic = idClinic;
	}

	public Clinic(int idClinic, String address, String nameClinic, Set<Doctor> doctors) {
		this.idClinic = idClinic;
		this.address = address;
		this.nameClinic = nameClinic;
		this.doctors = doctors;
	}
	
	public Clinic(String address, String nameClinic) {
		super();
		this.address = address;
		this.nameClinic = nameClinic;
	}

	public Clinic(int idClinic, String address, String nameClinic) {
		super();
		this.idClinic = idClinic;
		this.address = address;
		this.nameClinic = nameClinic;
	}

	public int getIdClinic() {
		return this.idClinic;
	}

	public void setIdClinic(int idClinic) {
		this.idClinic = idClinic;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getNameClinic() {
		return this.nameClinic;
	}

	public void setNameClinic(String nameClinic) {
		this.nameClinic = nameClinic;
	}

	public Set<Doctor> getDoctors() {
		return this.doctors;
	}

	public void setDoctors(Set<Doctor> doctors) {
		this.doctors = doctors;
	}

	@Override
	public String toString() {
		return "Clinic " + idClinic + "\taddress: " + address + "\t name: " + nameClinic;
	}
	
	

}
