package entity;
// Generated May 8, 2017 8:56:39 AM by Hibernate Tools 5.2.1.Final

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;

/**
 * Patient generated by hbm2java
 */
@Entity
public class Patient implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7593466296168954875L;
	@Id
	@GeneratedValue
	private int idPatient;
	@ManyToOne
	private Users users;
	private String namePatient;
	private Integer age;
	private Boolean gender;
	private String address;
	private Integer monthAge;

	public Patient() {
	}

	public Patient(Users users, String namePatient, Integer age, Boolean gender, String address, Integer monthAge) {
		super();
		this.users = users;
		this.namePatient = namePatient;
		this.age = age;
		this.gender = gender;
		this.address = address;
		this.monthAge = monthAge;
	}

	public Patient(int idPatient) {
		this.idPatient = idPatient;
	}

	public Patient(int idPatient, Users users, String namePatient, Integer age, Boolean gender, String address,
			Integer monthAge) {
		this.idPatient = idPatient;
		this.users = users;
		this.namePatient = namePatient;
		this.age = age;
		this.gender = gender;
		this.address = address;
		this.monthAge = monthAge;
	}

	public int getIdPatient() {
		return this.idPatient;
	}

	public void setIdPatient(int idPatient) {
		this.idPatient = idPatient;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getNamePatient() {
		return this.namePatient;
	}

	public void setNamePatient(String namePatient) {
		this.namePatient = namePatient;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public Boolean getGender() {
		return this.gender;
	}

	public void setGender(Boolean gender) {
		this.gender = gender;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getMonthAge() {
		return this.monthAge;
	}

	public void setMonthAge(Integer monthAge) {
		this.monthAge = monthAge;
	}

}
