package entity;
// Generated May 8, 2017 8:56:39 AM by Hibernate Tools 5.2.1.Final

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

import flexjson.JSONSerializer;

/**
 * Questionmessage generated by hbm2java
 */
@Entity
@XmlRootElement
public class Questionmessage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3816637729108485148L;
	@Id
	@GeneratedValue
	private int idMessage;
	@OneToOne()
	private Message message;
	@ManyToOne
	private Specialty specialty;

	public Questionmessage() {
	}

	public Questionmessage(Message message) {
		this.message = message;
	}

	public Questionmessage(Message message, Specialty specialty) {
		this.message = message;
		this.specialty = specialty;
	}

	public int getIdMessage() {
		return this.idMessage;
	}

	@XmlElement
	public void setIdMessage(int idMessage) {
		this.idMessage = idMessage;
	}

	public Message getMessage() {
		return this.message;
	}

	@XmlElement
	public void setMessage(Message message) {
		this.message = message;
	}

	public Specialty getSpecialty() {
		return this.specialty;
	}

	@XmlElement
	public void setSpecialty(Specialty specialty) {
		this.specialty = specialty;
	}
	public String toJson(){
		JSONSerializer js = new JSONSerializer();
		return js.serialize(this);
	}
}
