package entity;
// Generated May 8, 2017 8:56:39 AM by Hibernate Tools 5.2.1.Final

/**
 * Questionmessage generated by hbm2java
 */
public class Questionmessage implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3816637729108485148L;
	private int idMessage;
	private Message message;
	private Specialty specialty;

	public Questionmessage() {
	}
	
	public Questionmessage(Message message) {
		this.message = message;
	}

	public Questionmessage(Message message, Specialty specialty) {
		this.message = message;
		this.specialty = specialty;
	}

	public int getIdMessage() {
		return this.idMessage;
	}

	public void setIdMessage(int idMessage) {
		this.idMessage = idMessage;
	}

	public Message getMessage() {
		return this.message;
	}

	public void setMessage(Message message) {
		this.message = message;
	}

	public Specialty getSpecialty() {
		return this.specialty;
	}

	public void setSpecialty(Specialty specialty) {
		this.specialty = specialty;
	}

}
