package entity;
// Generated May 8, 2017 8:56:39 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;

/**
 * Reservation generated by hbm2java
 */
public class Reservation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5308229041711027457L;
	private int idReservation;
	private Doctor doctor;
	private Users users;
	private Date dates;
	private Boolean isConfirm;

	public Reservation() {
	}

	public Reservation(int idReservation) {
		this.idReservation = idReservation;
	}
	
	public Reservation(Doctor doctor, Users users, Date dates, Boolean isConfirm) {
		super();
		this.doctor = doctor;
		this.users = users;
		this.dates = dates;
		this.isConfirm = isConfirm;
	}

	public Reservation(int idReservation, Doctor doctor, Users users, Date dates, Boolean isConfirm) {
		this.idReservation = idReservation;
		this.doctor = doctor;
		this.users = users;
		this.dates = dates;
		this.isConfirm = isConfirm;
	}

	public int getIdReservation() {
		return this.idReservation;
	}

	public void setIdReservation(int idReservation) {
		this.idReservation = idReservation;
	}

	public Doctor getDoctor() {
		return this.doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public Date getDates() {
		return this.dates;
	}

	public void setDates(Date dates) {
		this.dates = dates;
	}

	public Boolean getIsConfirm() {
		return this.isConfirm;
	}

	public void setIsConfirm(Boolean isConfirm) {
		this.isConfirm = isConfirm;
	}

}
