package entity;
// Generated May 8, 2017 8:56:39 AM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Specialty generated by hbm2java
 */
public class Specialty implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8868335981988916560L;
	private int idSpecialty;
	private String nameSpecialty;
	private Set<Questionmessage> questionmessages = new HashSet<>(0);
	private Set<Doctor> doctors = new HashSet<>(0);

	public Specialty() {
	}

	public Specialty(int idSpecialty) {
		this.idSpecialty = idSpecialty;
	}

	public Specialty(int idSpecialty, String nameSpecialty) {
		super();
		this.idSpecialty = idSpecialty;
		this.nameSpecialty = nameSpecialty;
	}

	public Specialty(String nameSpecialty) {
		super();
		this.nameSpecialty = nameSpecialty;
	}

	public Specialty(int idSpecialty, String nameSpecialty, Set<Questionmessage> questionmessages,
			Set<Doctor> doctors) {
		super();
		this.idSpecialty = idSpecialty;
		this.nameSpecialty = nameSpecialty;
		this.questionmessages = questionmessages;
		this.doctors = doctors;
	}

	public int getIdSpecialty() {
		return this.idSpecialty;
	}

	public void setIdSpecialty(int idSpecialty) {
		this.idSpecialty = idSpecialty;
	}

	public String getNameSpecialty() {
		return this.nameSpecialty;
	}

	public void setNameSpecialty(String nameSpecialty) {
		this.nameSpecialty = nameSpecialty;
	}

	public Set<Questionmessage> getQuestionmessages() {
		return questionmessages;
	}

	public void setQuestionmessages(Set<Questionmessage> questionmessages) {
		this.questionmessages = questionmessages;
	}

	public Set<Doctor> getDoctors() {
		return doctors;
	}

	public void setDoctors(Set<Doctor> doctors) {
		this.doctors = doctors;
	}

}
