package entity;
// Generated May 8, 2017 8:56:39 AM by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;

/**
 * Users generated by hbm2java
 */
@Entity
public class Users implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3796766601258633930L;
	@Id
	@GeneratedValue
	private int idUser;
	private String email;
	private String passwords;
	private Date timeCreate;
	@OneToMany(mappedBy = "users")
	private Set<Reservation> reservations = new HashSet<>(0);
	@OneToMany(mappedBy = "users")
	private Set<Patient> patients = new HashSet<>(0);
	@OneToMany(mappedBy = "users")
	private Set<Message> messages = new HashSet<>(0);

	public Users() {
	}

	public Users(int idUser, Date timeCreate) {
		this.idUser = idUser;
		this.timeCreate = timeCreate;
	}

	public Users(int idUser, String email, String passwords, Date timeCreate) {
		super();
		this.idUser = idUser;
		this.email = email;
		this.passwords = passwords;
		this.timeCreate = timeCreate;
	}

	public Users(String email, String passwords, Date timeCreate) {
		super();
		this.email = email;
		this.passwords = passwords;
		this.timeCreate = timeCreate;
	}

	public Users(int idUser, String email, String passwords, Date timeCreate, Set<Reservation> reservations,
			Set<Patient> patients, Set<Message> messages) {
		super();
		this.idUser = idUser;
		this.email = email;
		this.passwords = passwords;
		this.timeCreate = timeCreate;
		this.reservations = reservations;
		this.patients = patients;
		this.messages = messages;
	}

	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPasswords() {
		return this.passwords;
	}

	public void setPasswords(String passwords) {
		this.passwords = passwords;
	}

	public Date getTimeCreate() {
		return this.timeCreate;
	}

	public void setTimeCreate(Date timeCreate) {
		this.timeCreate = timeCreate;
	}

	public Set<Reservation> getReservations() {
		return reservations;
	}

	public void setReservations(Set<Reservation> reservations) {
		this.reservations = reservations;
	}

	public Set<Patient> getPatients() {
		return patients;
	}

	public void setPatients(Set<Patient> patients) {
		this.patients = patients;
	}

	public Set<Message> getMessages() {
		return messages;
	}

	public void setMessages(Set<Message> messages) {
		this.messages = messages;
	}

}
